import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { AllWalletsProvider } from "@/services/wallets/AllWalletsProvider";
import NavBar from "@/components/Navbar";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("relative h-full font-sans antialised", inter.className)} suppressHydrationWarning={true}>
        <Providers>
          <main className="relative flex flex-col min-h-screen">
            <div className="flex-grow flex-1">
              {/* <AllWalletsProvider> */}
                <header>
                  <NavBar />
                </header>
                {children}
              {/* </AllWalletsProvider> */}
            </div>
          </main>
        </Providers>
      </body>
      
    </html>
  );
}
